### ISSUE TITLE
facet engine space problems

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#113]
So unfortunately the D X Ngram matrix written for the lens corpus starts getting big. keeping all the counts in memory allows for fast queries but is not feasible for larger corpora. 

matrix is 100 GB serialized for a larger corpus of 120,000 docs.

one option might be constructing a submatrix from a DB on the fly at query time by pulling only columns that match query-responsive documents.

**Comment by AbeHandler** [comment]
On 1.29.16 Abe and Brendan discussed replacing the full ngram X document matrix with a sparse vector data structure for each document. Each of these sparse vectors could be held in memory and then added w/ python (or cython function).

![img_20160129_115602](https://cloud.githubusercontent.com/assets/1252925/12689835/4725f092-c6ad-11e5-9716-d75605385b65.jpg)

**Comment by AbeHandler** [comment]
the solution we discussed above seems to work. closing this.

**Comment by brendano** [comment]
awesome.  i realize one thing i forgot to say: so it sounded like the term vectors only need to have binary indicators of term presence.  this means another 2x space savings, by only storing a vector of termIDs of terms that are present in the document. the values vector (storing the counts of each) is unnecessary since it's always 1.  of course a 2x savings isn't that much compared to the big gains of using the smart sparse representation.

**Comment by AbeHandler** [comment]
good point. for now: I'm not even messing around w/ numpy vectors. just using python dicts dumped into postgres and then added one by one into memory on load.
