### ISSUE TITLE
Compact date representation in code

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#125]
https://github.com/mbostock/d3/wiki/Time-Scales

**Comment by brendano** [comment]
bostock's API here is really nice. i've hacked together the time interval creation functions a thousand times with strftime/strptime and it is not fun

**Comment by AbeHandler** [comment]
@brendano a few things on dates ... 

1. this library is great btw: http://momentjs.com/docs/
2. React won't let you use an object as a state/prop (I think b/c are mutable). I am passing 6 parameters around all over the place (t_start_yr, t_start_mo ... t_end_day ... etc) which is a huge pain. Any suggestions there would help a bunch to simplify code.

**Comment by brendano** [comment]
pass around a more compact representation ... like a string repr?  or a unix timestamp (integer num seconds since the "epoch")?

e.g. date2str() and str2date() and always pass around strs, but immediately convert to Dates when necessary.

for str reprs i'd say use a strptime/strftime representation of "%Y-%m-%d" (a subset of ISO8601 %Y-%m-%dT%H:%M:%S which is obviously the best encoding for datetimes) but looks like js doesnt have em? or do it manually.  or separate with a space. whatever

**Comment by brendano** [comment]
oh now i see momentjs k

**Comment by brendano** [comment]
wait does react forbid objects as props? or is it the docs don't like it and complain about it and heavily advise to always treat objects as immutable? that was my reading of https://facebook.github.io/react/docs/jsx-spread.html ... you could use objects all you want, but in order for react to know of a change, you can't mutate the object, instead replace it with a whole new one? they have "immutability helpers" stuff in there to aid in this so it's not quite so nonconvenient
