### ISSUE TITLE
Snippet logic too slow

### ISSUE THREAD

**Issue by AbeHandler** [AbeHandler/rookie#154]
it takes ~10 ms per doc to loop thru all sentences and find the sentences that store q and f. This is taking too long (ex ~3 secs for 300 docs). need to index what ngrams are in what sentences and do a lookup.

Could you replicate the sparse vector thing from facets? I.e. store sparse matrixes of ngrams by sentence for each doc and fit in memory?

Gawker has 48761 ngrams.

**Comment by AbeHandler** [comment]
hrm. this is trickier. you'd have to index unigrams as well as ngrams b/c ppl could query anything. still, the datastructure would be very sparse. gonna try it

**Comment by AbeHandler** [comment]
get_doc_metadata in models.py was the bottleneck. the function makes a call to postgres, which was slow -- even with indexes set on the db. 

I tried a more complex custom indexing thing thinking that the problem was searching thru the sentences to make a a snippet, when in fact the problem was plucking them from the db in the first place. 

In any event, just adding @lrudecorator(3000) above the get doc metadata function basically solves this for the lens corpus.

**Comment by brendano** [comment]
are you saying this was slow?  from webapp/models.py:
```select data from doc_metadata where docid=%s and corpusid=%s", docid, corpusid)```

yeah, so indexing might be only part of this, esp since the table is pretty small (100k).  a possible bottleneck is getting the data going out of the db into python. deserialization or something like that might be an issue?

how many times does `get_doc_metadata` get called?
 - to pull the data for one row i'm seeing 0.8ms.
 - to pull just the ids for one row i'm seeing 0.1ms.

this is with psycopg2 directly.

setup:
```
conn=psycopg2.connect("dbname='rookie' user='rookie'")
c=conn.cursor()
In [51]: def go1(sql):
   ....:     c.execute(sql)
   ....:     return iter(c).next()
```

**Timings.**  This is ipython's `%timeit` "magic" command.

```
In [52]: timeit go1("select docid from doc_metadata where docid=116354 and corpusid=2")
The slowest run took 6.12 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 96 µs per loop

In [53]: timeit go1("select data from doc_metadata where docid=116354 and corpusid=2")
1000 loops, best of 3: 852 µs per loop
```


Another test: randomly choose a docid (from a pre-made python list which is quite fast to do) then get it from the db.
This gets basically the same results.

```
c.execute("select docid,corpusid from doc_metadata")
dc_ids=list(c)

In [48]: def go(sel):
    docid,cid=random.choice(dc_ids)
    c.execute("select %s from doc_metadata where docid=%s and corpusid=%s" % (sel, docid, cid))
    return iter(c).next()

In [46]: timeit go("data")
1000 loops, best of 3: 790 µs per loop

In [50]: timeit go("docid")
10000 loops, best of 3: 120 µs per loop
```

And to confirm a python list lookup is a gazillion times faster than going to postgres:
```
In [55]: timeit random.choice(dc_ids)
The slowest run took 78.03 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 474 ns per loop
```

 - ms = millisec, 10^-3
 - µs = microsec, 10^-6
 - ns = nanosec, 10^-9

**Comment by brendano** [comment]
sorry that python list lookup part is silly as a comparison.  it's not doing an actual search (all it does is confirm that that part within the testing infrastructure doesnt add much overhead).

actually doing a linear lookup is slow.  i dont have the real data anymore after the db reset so faked it

```
In [15]: dc_ids=[(d,-1) for d in range(120000)]
In [15]: random.shuffle(dc_ids)
In [15]: timeit [docid for (docid,cid) in dc_ids if docid==116354]
100 loops, best of 3: 7.3 ms per loop
```

a python index, though, is way faster than postgres.
```
In [16]: idx={docid:(docid,cid) for (docid,cid) in dc_ids}

In [17]: timeit idx[116354]
The slowest run took 61.23 times longer than the fastest. This could mean that an intermediate result is being cached 
10000000 loops, best of 3: 50.6 ns per loop
```

and of course storing more data in each tuple as python objects wont slow this down since it's all native stuff within the python interpreter.  crossing the boundary of shoving data from postgres into the python interpreter has all sorts of perf implications.

**Comment by AbeHandler** [comment]
@brendano in this case, what we need from the DB is the raw text for each sentence in each query-responsive doc. To do what you're suggesting we'd just keep that all in memory (python dict), right? I guess this is fine for the Lens (and I would have to check for gawker). But has limits w/ scale.

**Comment by brendano** [comment]
Right, keeping it all in-memory in the interpreter doesn't scale too far.

I guess there are three possible slowdowns for these postgres queries compared to in-memory dict access
1. Disk (instead of RAM)
2. Query overhead (going through all the layers of the postgres subsystems)
3. Deserialization (vs native python structured with pointers already arranged and all that)

For some reason I wasn't thinking about (1).  Hm, if it really is disk access that's the bottleneck there's not much we can do.  (Assuming we want an architecture that relies heavily on disk, which is surely a good bet. As opposed to John who's been looking at an SSD-based system.)  I think I was worried about (2) that postgres may be sacrificing efficiency when doing lots of little queries just from the overhead of a single query, which could be addressed with a different lower-level data/store system (e.g. key-value stores or lucene etc). And then I mentioned (3).  But this is speculative.

The LRU decorator with a large cache is basically just loading some or all of the corpus into memory.  A great trick if it all fits, or the access pattern is such that a small subset of the data gets re-accessed many times.

**Comment by AbeHandler** [comment]
@brendano @myersnews said that the 3/24 version still felt pretty slow. 

One obvious thing to do is start caching stuff you might need for particular facets as soon as you return the initial web request. I tried this once using the python thread module -- but found the following problem.

Say warming up the cache takes 3 or 5 seconds. Say the user clicks a facet after 1/2 a second. Clicking the facet POSTs back for the Q,F,T, sentences. The server process is still warming up the cache. so it makes the new POST request wait. so basically you need a way of giving new incoming web requests priority over old cache warming threads. if you know an easy way to do that: it would help a bunch.

**Comment by myersnews** [comment]
I have no feedback on that particular issue, but I do think that most users will take more than 1/2 second to pick something.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by brendano** [comment]
if you're using python threads, you basically have to kill the cache warming jobs.  python interpreter is effectively single threaded.  only one thread can do anything real at once.  (the only thing python threads really can do is wait on I/O.)  

however that model might work ok here.  it will require diving into python threading modules and will be difficult to debug, though.

python multiprocessing approaches tend to work a bit better.  but then you need a sharable thing between python processes.  you've already found that postgres is too slow and got big gains putting caching within the python interpreter.  we'd need to find a new outside-of-python tech to do this ... e.g. redis ... stuff python pickles into it maybe.  ugh.  tricky.  (and also a way to communicate between the processes to tell the cache-warmer what to do.  similar trickiness as python threading though intuitively seems less tricky to me, not sure why. threads are weird.)

**Comment by AbeHandler** [comment]
uh... webapp spawns a process which fills a redis cache which the webapp then checks before going to postgres. 

oh lord.

**Comment by brendano** [comment]
slight simplification of this idea: can postgres hold a cache of more-processed data that's faster to use than the less-processed data that postgres currently holds?  not a huge simplification but cuts out the need for a redis server ...

since we're doing everything in-process right now, python threads and the within-interpreter cache might be the best way to go.  this will not scale to hundreds of users, but may work fine with <5 or <10 which is where we are now

**Comment by AbeHandler** [comment]
hrm. so we think the bottleneck is caused by some combo of (1) seek cost (2) deserialization cost

If (2) is the real bottleneck, then we could store each sentence as its own record in postgres. build an index of what unigrams are in what sentence. use the index to reason about what sentences to pull. (or build a small list of candidates) and then pull them from the db. If (1) is the bottleneck, this won't help at all tho. I tried this unsystematically a week ago and it did not seem to help, but was at the time was hacking around trying to make it go faster rather than carefully measuring things.

**Comment by AbeHandler** [comment]
ah. ok so I tried both the (1) store preprocesed sentences in postgres method and the (2) redis subprocess method. The speed gains are about the same for each and the redis method is more complex -- so let's do the postgres method for now. 

(I guess it would make sense for the speed to be about the same because the cost of a postgres lookup is roughly the same as the cost of a redis lookup -- and the deserialization cost in both cases is the same (because each stores sentences that have been preprocessed into a long string, eliminating json deserialization costs). So this is sort of postgres as cache.) 

Some informal benchmark numbers with the in-process @lrucache decorator turned OFF: 
The wait time on get_sents method is about 800ms for Q=Mitch Landrieu and corpus=lens. Similar wait time for Q=Mitch Landrieu, F=Marlin Gusman. (counting wait time, not wait time + download time). 

Not sure if this method will work for larger corpora (ex. Q=Donald Trump returns 900 docs rather than the 300 for landrieu) so keeping this open + keeping redis code in the repo.

**Also: the old method was making a call to postgres to get the headline for each doc. now headlines have their own index. this helps a BUNCH as well **

**Comment by brendano** [comment]
can postgres (or whatever storage system) be made to store the same
information that the "@"lrucache decorator stores, or something close?  i'm
assuming the lrucache decorator uses pickle or something like that, on the
most usable, post-processed, form of the data.  this could just be a binary
blob within postgres.

but it could be the case the deserialization time is still high here. i'm
not sure.  i guess i was worried about the translation between the format
in the DB, versus the objects that the application code users, as a reason
for the difference between the decorator versus caching in an external
storage system.
