### ISSUE TITLE
hand pointer for clickable things

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#189]
as long as we're doing small UI changes

`cursor: pointer` for facet text spans would be nice to indicate they're clickable.

**Comment by AbeHandler** [comment]
by "facet text spans" do you mean these things? In UI terms I call those things "SparklineTiles" for what its worth

<img width="1280" alt="screen shot 2016-03-24 at 5 29 57 pm" src="https://cloud.githubusercontent.com/assets/1252925/14031978/118597ee-f1e6-11e5-8142-efe3cc29d3b1.png">

**Comment by brendano** [comment]
i mean the text that is dark red.

On Thursday, March 24, 2016, Abe Handler <notifications@github.com> wrote:

> by "facet text spans" do you mean these things? In UI terms I call those
> things "SparklineTiles" for what its worth
>
> [image: screen shot 2016-03-24 at 5 29 57 pm]
> <https://cloud.githubusercontent.com/assets/1252925/14031978/118597ee-f1e6-11e5-8142-efe3cc29d3b1.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AbeHandler/rookie/issues/189#issuecomment-201032092>
>


-- 
-brendan [mobile]

**Comment by brendano** [comment]
ah found another place to have the pointer cursor: the [x] boxes

<img width="408" alt="screen shot 2016-03-24 at 7 45 16 pm" src="https://cloud.githubusercontent.com/assets/1677/14034382/2205f61e-f1f9-11e5-96d6-e5cbf977a0a9.png">

(maybe it's just me but i find it nonintuitive that when the cursor is in text selection mode, that i'm supposed to click)

**Comment by brendano** [comment]
another one, the "summarize" on the right here

<img width="1136" alt="screen shot 2016-03-24 at 7 49 18 pm" src="https://cloud.githubusercontent.com/assets/1677/14034423/88fdc3f6-f1f9-11e5-9ea3-525cd4b22f4e.png">

**Comment by myersnews** [comment]
I agree.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Mar 24, 2016, at 6:48 PM, brendano <notifications@github.com> wrote:

ah found another place to have the pointer cursor: the [x] boxes

[image: screen shot 2016-03-24 at 7 45 16 pm]
<https://cloud.githubusercontent.com/assets/1677/14034382/2205f61e-f1f9-11e5-96d6-e5cbf977a0a9.png>

(maybe it's just me but i find it nonintuitive that when the cursor is in
text selection mode, that i'm supposed to click)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/AbeHandler/rookie/issues/189#issuecomment-201075988>
